services:
  dcmr:
    image: dcmr
    build:
      context: .
      dockerfile: DCMR/DCMR/Dockerfile

  dcmr.client:
    image: dcmr.client
    build:
      context: .
      dockerfile: DCMR/DCMR.Client/Dockerfile

